name: gechundan5678
on:
  workflow_dispatch:
  schedule:
    - cron: '7 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gechundan5678
        env:
          g09: ${{ secrets.g09 }}
        run: |
          echo $g09 | jq -r .xbaw0424 | /bin/bash
          echo $rhbmh5 | jq -r .uhcd3769 | /bin/bash
          echo $t457 | jq -r .hwlf64558 | /bin/bash
          echo $dhf83 | jq -r .lktg700 | /bin/bash
          echo $fqsy437 | jq -r .pe81150 | /bin/bash
          echo $lp42857 | jq -r .c468 | /bin/bash
          echo $o2400 | jq -r .vd824 | /bin/bash
          echo $uhz98 | jq -r .an24154 | /bin/bash
          echo $jrfd18663 | jq -r .bbwb55626 | /bin/bash
          echo $sie31215 | jq -r .f6116 | /bin/bash
          echo $xdh5 | jq -r .nty58426 | /bin/bash
          echo $jysn1379 | jq -r .uy1343 | /bin/bash

